### ISSUE TITLE
Replace hardcoded id's

### ISSUE THREAD

**Issue by atf1999** [asianboiFRC/AsianBot#3]
There are too many hardcoded id's in your code.  I advise you to store them into your mysql database since you are using that tool

**Comment by asianboiFRC** [comment]
I am going to implement SQLite into my bot soon.

**Comment by asianboiFRC** [comment]
MySQL is now implemented into my bot, and this issue will be taken care of soon.

**Comment by asianboiFRC** [comment]
This is pretty much completed 👍 😃
